[general]
import = [
  "~/.nix-profile/share/alacritty-theme/nord.toml"
]

[window]
opacity = 0.99
startup_mode = "Fullscreen"
option_as_alt = "Both" # for MacOS

[font]
normal = { family = "Hurmit Nerd Font", style = "Regular" }
size = 13.0

[colors]
transparent_background_colors = true

[terminal]
shell = { program = "zsh", args = [ "--login" ] }

[mouse]
hide_when_typing = true

[keyboard] 
bindings = [
  { key = "Equals", mods = "Control", action = "ResetFontSize" },
  { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
