# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	{ on = [ ",", "m" ], run = "escape", desc = "Exit visual mode, clear selection, or cancel search" },

	# Sorting
	{ on = [ ",", "t" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
	{ on = [ ",", "T" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },

	# Tabs
	{ on = "<A-t>", run = "tab_create --current", desc = "Create a new tab with CWD" },
	{ on = "H", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = "L", run = "tab_switch 1 --relative",  desc = "Switch to next tab" },
	{ on = "(", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
	{ on = ")", run = "tab_swap 1",  desc = "Swap current tab with next tab" },
]

[tasks]
prepend_keymap = [
	{ on = [ ",", "m" ], run = "close", desc = "Close task manager" },
]


[cmp]
prepend_keymap = [
	{ on = "<C-k>", run = "arrow prev", desc = "Previous item" },
	{ on = "<C-j>", run = "arrow next", desc = "Next item" },
]
