name: base
dependencies:
  - conda-forge::bat=0.25.*
  - conda-forge::curl=8.13.*
  - conda-forge::fd-find=10.2.*
  - conda-forge::fzf=0.62.*
  - conda-forge::git-delta=0.18.*
  - conda-forge::git=2.49.*
  - conda-forge::jq=1.7.*
  - conda-forge::nvim=0.11.*
  - conda-forge::ripgrep=14.1.*
  - conda-forge::starship=1.23.*
  - conda-forge::stow=2.3.*
  - conda-forge::tig=2.5.*
  - conda-forge::tmux=3.5.*
  - conda-forge::yq=3.4.*
  - conda-forge::zsh=5.9.*
