vim.keymap.set({'n'} , '<leader>zz', require("fzf-lua").builtin)
vim.keymap.set({'n'} , '<leader>f', require("fzf-lua").files)
vim.keymap.set({'n'} , '<leader>g', require("fzf-lua").grep_project)
vim.keymap.set({'n'} , '<leader>G', require("fzf-lua").grep)
vim.keymap.set({'n'} , '<leader>l', require("fzf-lua").blines)
vim.keymap.set({'n'} , '<leader>b', require("fzf-lua").buffers)
vim.keymap.set({'n'} , '<leader>h', require("fzf-lua").help_tags)
