name: local

channels: 
  - conda-forge

# no curl, no git because it seems they are compiled such that they resolve SSL certificate from the conda environment
dependencies:
  - conda-forge::tig
  - conda-forge::tmux
  - conda-forge::zsh
